### GET request to example server
POST http://localhost:8080/api/bots/24591cd1-2ece-439f-b843-6235fc6b6f5d/ask

{
  "question": "Who is Americas president?"
}

###
GET https://generativelanguage.googleapis.com/v1beta/models?key=GEMINI_API_KEY

###