###
GET https://generativelanguage.googleapis.com/v1beta/models?key=GEMINI_API_KEY

### GET request to example server
###
POST http://localhost:8080/api/bots/widget/ask?botId=botId
Content-Type: application/json

{
  "message": "What is your purpose?",
  "history": [
    {
    }
  ]
}